### ISSUE TITLE
chef 12 new error

### ISSUE THREAD

**Issue by blueharford** [bmarini/knife-inspect#38]
.chefdk/gem/ruby/2.1.0/gems/knife-inspect-0.12.0/lib/health_inspector/checklists/cookbooks.rb:45:in `block (2 levels) in validate_changes_on_the_server_not_in_the_repo': undefined method `join' for nil:NilClass (NoMethodError)
	from /Users/jseidel/.chefdk/gem/ruby/2.1.0/gems/knife-inspect-0.12.0/lib/health_inspector/checklists/cookbooks.rb:44:in `each'
	from /Users/jseidel/.chefdk/gem/ruby/2.1.0/gems/knife-inspect-0.12.0/lib/health_inspector/checklists/cookbooks.rb:44:in `block in validate_changes_on_the_server_not_in_the_repo'
	from /Users/jseidel/.chefdk/gem/ruby/2.1.0/gems/knife-inspect-0.12.0/lib/health_inspector/checklists/cookbooks.rb:43:in `each'
	from /Users/jseidel/.chefdk/gem/ruby/2.1.0/gems/knife-inspect-0.12.0/lib/health_inspector/checklists/cookbooks.rb:43:in `validate_changes_on_the_server_not_in_the_repo'
	from /Users/jseidel/.chefdk/gem/ruby/2.1.0/gems/knife-inspect-0.12.0/lib/health_inspector/pairing.rb:30:in `block in validate'
	from /Users/jseidel/.chefdk/gem/ruby/2.1.0/gems/knife-inspect-0.12.0/lib/health_inspector/pairing.rb:30:in `each'
	from /Users/jseidel/.chefdk/gem/ruby/2.1.0/gems/knife-inspect-0.12.0/lib/health_inspector/pairing.rb:30:in `validate'
	from /Users/jseidel/.chefdk/gem/ruby/2.1.0/gems/knife-inspect-0.12.0/lib/health_inspector/checklists/base.rb:59:in `validate_item'
	from /Users/jseidel/.chefdk/gem/ruby/2.1.0/gems/knife-inspect-0.12.0/lib/health_inspector/checklists/base.rb:45:in `load_validate'
	from /Users/jseidel/.chefdk/gem/ruby/2.1.0/gems/knife-inspect-0.12.0/lib/health_inspector/checklists/base.rb:52:in `block in run'
	from /Users/jseidel/.chefdk/gem/ruby/2.1.0/gems/parallel-1.3.4/lib/parallel.rb:430:in `call'
	from /Users/jseidel/.chefdk/gem/ruby/2.1.0/gems/parallel-1.3.4/lib/parallel.rb:430:in `call_with_index'
	from /Users/jseidel/.chefdk/gem/ruby/2.1.0/gems/parallel-1.3.4/lib/parallel.rb:336:in `process_incoming_jobs'
	from /Users/jseidel/.chefdk/gem/ruby/2.1.0/gems/parallel-1.3.4/lib/parallel.rb:318:in `block in worker'
	from /Users/jseidel/.chefdk/gem/ruby/2.1.0/gems/parallel-1.3.4/lib/parallel.rb:311:in `fork'
	from /Users/jseidel/.chefdk/gem/ruby/2.1.0/gems/parallel-1.3.4/lib/parallel.rb:311:in `worker'
	from /Users/jseidel/.chefdk/gem/ruby/2.1.0/gems/parallel-1.3.4/lib/parallel.rb:299:in `block in create_workers'
	from /Users/jseidel/.chefdk/gem/ruby/2.1.0/gems/parallel-1.3.4/lib/parallel.rb:298:in `each'
	from /Users/jseidel/.chefdk/gem/ruby/2.1.0/gems/parallel-1.3.4/lib/parallel.rb:298:in `create_workers'
	from /Users/jseidel/.chefdk/gem/ruby/2.1.0/gems/parallel-1.3.4/lib/parallel.rb:255:in `work_in_processes'
	from /Users/jseidel/.chefdk/gem/ruby/2.1.0/gems/parallel-1.3.4/lib/parallel.rb:191:in `map'
	from /Users/jseidel/.chefdk/gem/ruby/2.1.0/gems/knife-inspect-0.12.0/lib/health_inspector/checklists/base.rb:51:in `run'
	from /Users/jseidel/.chefdk/gem/ruby/2.1.0/gems/knife-inspect-0.12.0/lib/health_inspector/checklists/base.rb:20:in `run'
	from /Users/jseidel/.chefdk/gem/ruby/2.1.0/gems/knife-inspect-0.12.0/lib/chef/knife/inspect.rb:18:in `block in run'
	from /Users/jseidel/.chefdk/gem/ruby/2.1.0/gems/knife-inspect-0.12.0/lib/chef/knife/inspect.rb:17:in `map'
	from /Users/jseidel/.chefdk/gem/ruby/2.1.0/gems/knife-inspect-0.12.0/lib/chef/knife/inspect.rb:17:in `run'
	from /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.0.3/lib/chef/knife.rb:417:in `block in run_with_pretty_exceptions'
	from /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.0.3/lib/chef/local_mode.rb:38:in `with_server_connectivity'
	from /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.0.3/lib/chef/knife.rb:416:in `run_with_pretty_exceptions'
	from /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.0.3/lib/chef/knife.rb:213:in `run'
	from /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.0.3/lib/chef/application/knife.rb:139:in `run'
	from /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.0.3/bin/knife:25:in `<top (required)>'
	from /opt/chefdk/embedded/bin/knife:23:in `load'
	from /opt/chefdk/embedded/bin/knife:23:in `<main>'

**Comment by gregkare** [comment]
Hi,

I'm not sure yet why that variable is set to`nil` but I found the bug. I'm writing a test for it and I'll fix it and release a new version (probably tonight).

Thanks for reporting it! Do you know which cookbook it happens for?

**Comment by gregkare** [comment]
@blueharford Sorry I took so long to get back to you.

Can you try the fix_cookbook_crash branch I've created? It should at least give more information about which cookbook made it crash.

The easiest way is to change your Gemfile to get it from the branch:

```ruby
gem 'knife-inspect',   github: 'bmarini/knife-inspect', branch: 'fix_cookbook_crash'
```

Thanks! Please submit a full stack trace in a Gist

**Comment by blueharford** [comment]
i ran that, and it doesnt work
